# Generated by Django 3.0.4 on 2020-03-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
